// flow-typed signature: 8959f2455ea29fdace7143faeafa9df4
// flow-typed version: <<STUB>>/@octokit/request_v^6.2.1/flow_v0.184.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@octokit/request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@octokit/request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@octokit/request/dist-node' {
  declare module.exports: any;
}

declare module '@octokit/request/dist-src/fetch-wrapper' {
  declare module.exports: any;
}

declare module '@octokit/request/dist-src/get-buffer-response' {
  declare module.exports: any;
}

declare module '@octokit/request/dist-src' {
  declare module.exports: any;
}

declare module '@octokit/request/dist-src/version' {
  declare module.exports: any;
}

declare module '@octokit/request/dist-src/with-defaults' {
  declare module.exports: any;
}

declare module '@octokit/request/dist-web' {
  declare module.exports: any;
}

// Filename aliases
declare module '@octokit/request/dist-node/index' {
  declare module.exports: $Exports<'@octokit/request/dist-node'>;
}
declare module '@octokit/request/dist-node/index.js' {
  declare module.exports: $Exports<'@octokit/request/dist-node'>;
}
declare module '@octokit/request/dist-src/fetch-wrapper.js' {
  declare module.exports: $Exports<'@octokit/request/dist-src/fetch-wrapper'>;
}
declare module '@octokit/request/dist-src/get-buffer-response.js' {
  declare module.exports: $Exports<'@octokit/request/dist-src/get-buffer-response'>;
}
declare module '@octokit/request/dist-src/index' {
  declare module.exports: $Exports<'@octokit/request/dist-src'>;
}
declare module '@octokit/request/dist-src/index.js' {
  declare module.exports: $Exports<'@octokit/request/dist-src'>;
}
declare module '@octokit/request/dist-src/version.js' {
  declare module.exports: $Exports<'@octokit/request/dist-src/version'>;
}
declare module '@octokit/request/dist-src/with-defaults.js' {
  declare module.exports: $Exports<'@octokit/request/dist-src/with-defaults'>;
}
declare module '@octokit/request/dist-web/index' {
  declare module.exports: $Exports<'@octokit/request/dist-web'>;
}
declare module '@octokit/request/dist-web/index.js' {
  declare module.exports: $Exports<'@octokit/request/dist-web'>;
}
