// flow-typed signature: 379d3d96f6163e3ce10ec05a29f8b9c8
// flow-typed version: <<STUB>>/axios_v^1.1.2/flow_v0.184.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axios/bin/ssl_hotfix' {
  declare module.exports: any;
}

declare module 'axios/dist/axios' {
  declare module.exports: any;
}

declare module 'axios/dist/axios.min' {
  declare module.exports: any;
}

declare module 'axios/dist/esm/axios' {
  declare module.exports: any;
}

declare module 'axios/dist/esm/axios.min' {
  declare module.exports: any;
}

declare module 'axios/gulpfile' {
  declare module.exports: any;
}

declare module 'axios/lib/adapters/http' {
  declare module.exports: any;
}

declare module 'axios/lib/adapters' {
  declare module.exports: any;
}

declare module 'axios/lib/adapters/xhr' {
  declare module.exports: any;
}

declare module 'axios/lib/axios' {
  declare module.exports: any;
}

declare module 'axios/lib/cancel/CanceledError' {
  declare module.exports: any;
}

declare module 'axios/lib/cancel/CancelToken' {
  declare module.exports: any;
}

declare module 'axios/lib/cancel/isCancel' {
  declare module.exports: any;
}

declare module 'axios/lib/core/Axios' {
  declare module.exports: any;
}

declare module 'axios/lib/core/AxiosError' {
  declare module.exports: any;
}

declare module 'axios/lib/core/AxiosHeaders' {
  declare module.exports: any;
}

declare module 'axios/lib/core/buildFullPath' {
  declare module.exports: any;
}

declare module 'axios/lib/core/dispatchRequest' {
  declare module.exports: any;
}

declare module 'axios/lib/core/InterceptorManager' {
  declare module.exports: any;
}

declare module 'axios/lib/core/mergeConfig' {
  declare module.exports: any;
}

declare module 'axios/lib/core/settle' {
  declare module.exports: any;
}

declare module 'axios/lib/core/transformData' {
  declare module.exports: any;
}

declare module 'axios/lib/defaults' {
  declare module.exports: any;
}

declare module 'axios/lib/defaults/transitional' {
  declare module.exports: any;
}

declare module 'axios/lib/env/classes/FormData' {
  declare module.exports: any;
}

declare module 'axios/lib/env/data' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/AxiosTransformStream' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/AxiosURLSearchParams' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/bind' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/buildURL' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/combineURLs' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/cookies' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/deprecatedMethod' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/formDataToJSON' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/fromDataURI' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/isAbsoluteURL' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/isAxiosError' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/isURLSameOrigin' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/null' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/parseHeaders' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/parseProtocol' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/speedometer' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/spread' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/throttle' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/toFormData' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/toURLEncodedForm' {
  declare module.exports: any;
}

declare module 'axios/lib/helpers/validator' {
  declare module.exports: any;
}

declare module 'axios/lib/platform/browser/classes/FormData' {
  declare module.exports: any;
}

declare module 'axios/lib/platform/browser/classes/URLSearchParams' {
  declare module.exports: any;
}

declare module 'axios/lib/platform/browser' {
  declare module.exports: any;
}

declare module 'axios/lib/platform' {
  declare module.exports: any;
}

declare module 'axios/lib/platform/node/classes/FormData' {
  declare module.exports: any;
}

declare module 'axios/lib/platform/node/classes/URLSearchParams' {
  declare module.exports: any;
}

declare module 'axios/lib/platform/node' {
  declare module.exports: any;
}

declare module 'axios/lib/utils' {
  declare module.exports: any;
}

declare module 'axios/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axios/bin/ssl_hotfix.js' {
  declare module.exports: $Exports<'axios/bin/ssl_hotfix'>;
}
declare module 'axios/dist/axios.js' {
  declare module.exports: $Exports<'axios/dist/axios'>;
}
declare module 'axios/dist/axios.min.js' {
  declare module.exports: $Exports<'axios/dist/axios.min'>;
}
declare module 'axios/dist/esm/axios.js' {
  declare module.exports: $Exports<'axios/dist/esm/axios'>;
}
declare module 'axios/dist/esm/axios.min.js' {
  declare module.exports: $Exports<'axios/dist/esm/axios.min'>;
}
declare module 'axios/gulpfile.js' {
  declare module.exports: $Exports<'axios/gulpfile'>;
}
declare module 'axios/index' {
  declare module.exports: $Exports<'axios'>;
}
declare module 'axios/index.js' {
  declare module.exports: $Exports<'axios'>;
}
declare module 'axios/lib/adapters/http.js' {
  declare module.exports: $Exports<'axios/lib/adapters/http'>;
}
declare module 'axios/lib/adapters/index' {
  declare module.exports: $Exports<'axios/lib/adapters'>;
}
declare module 'axios/lib/adapters/index.js' {
  declare module.exports: $Exports<'axios/lib/adapters'>;
}
declare module 'axios/lib/adapters/xhr.js' {
  declare module.exports: $Exports<'axios/lib/adapters/xhr'>;
}
declare module 'axios/lib/axios.js' {
  declare module.exports: $Exports<'axios/lib/axios'>;
}
declare module 'axios/lib/cancel/CanceledError.js' {
  declare module.exports: $Exports<'axios/lib/cancel/CanceledError'>;
}
declare module 'axios/lib/cancel/CancelToken.js' {
  declare module.exports: $Exports<'axios/lib/cancel/CancelToken'>;
}
declare module 'axios/lib/cancel/isCancel.js' {
  declare module.exports: $Exports<'axios/lib/cancel/isCancel'>;
}
declare module 'axios/lib/core/Axios.js' {
  declare module.exports: $Exports<'axios/lib/core/Axios'>;
}
declare module 'axios/lib/core/AxiosError.js' {
  declare module.exports: $Exports<'axios/lib/core/AxiosError'>;
}
declare module 'axios/lib/core/AxiosHeaders.js' {
  declare module.exports: $Exports<'axios/lib/core/AxiosHeaders'>;
}
declare module 'axios/lib/core/buildFullPath.js' {
  declare module.exports: $Exports<'axios/lib/core/buildFullPath'>;
}
declare module 'axios/lib/core/dispatchRequest.js' {
  declare module.exports: $Exports<'axios/lib/core/dispatchRequest'>;
}
declare module 'axios/lib/core/InterceptorManager.js' {
  declare module.exports: $Exports<'axios/lib/core/InterceptorManager'>;
}
declare module 'axios/lib/core/mergeConfig.js' {
  declare module.exports: $Exports<'axios/lib/core/mergeConfig'>;
}
declare module 'axios/lib/core/settle.js' {
  declare module.exports: $Exports<'axios/lib/core/settle'>;
}
declare module 'axios/lib/core/transformData.js' {
  declare module.exports: $Exports<'axios/lib/core/transformData'>;
}
declare module 'axios/lib/defaults/index' {
  declare module.exports: $Exports<'axios/lib/defaults'>;
}
declare module 'axios/lib/defaults/index.js' {
  declare module.exports: $Exports<'axios/lib/defaults'>;
}
declare module 'axios/lib/defaults/transitional.js' {
  declare module.exports: $Exports<'axios/lib/defaults/transitional'>;
}
declare module 'axios/lib/env/classes/FormData.js' {
  declare module.exports: $Exports<'axios/lib/env/classes/FormData'>;
}
declare module 'axios/lib/env/data.js' {
  declare module.exports: $Exports<'axios/lib/env/data'>;
}
declare module 'axios/lib/helpers/AxiosTransformStream.js' {
  declare module.exports: $Exports<'axios/lib/helpers/AxiosTransformStream'>;
}
declare module 'axios/lib/helpers/AxiosURLSearchParams.js' {
  declare module.exports: $Exports<'axios/lib/helpers/AxiosURLSearchParams'>;
}
declare module 'axios/lib/helpers/bind.js' {
  declare module.exports: $Exports<'axios/lib/helpers/bind'>;
}
declare module 'axios/lib/helpers/buildURL.js' {
  declare module.exports: $Exports<'axios/lib/helpers/buildURL'>;
}
declare module 'axios/lib/helpers/combineURLs.js' {
  declare module.exports: $Exports<'axios/lib/helpers/combineURLs'>;
}
declare module 'axios/lib/helpers/cookies.js' {
  declare module.exports: $Exports<'axios/lib/helpers/cookies'>;
}
declare module 'axios/lib/helpers/deprecatedMethod.js' {
  declare module.exports: $Exports<'axios/lib/helpers/deprecatedMethod'>;
}
declare module 'axios/lib/helpers/formDataToJSON.js' {
  declare module.exports: $Exports<'axios/lib/helpers/formDataToJSON'>;
}
declare module 'axios/lib/helpers/fromDataURI.js' {
  declare module.exports: $Exports<'axios/lib/helpers/fromDataURI'>;
}
declare module 'axios/lib/helpers/isAbsoluteURL.js' {
  declare module.exports: $Exports<'axios/lib/helpers/isAbsoluteURL'>;
}
declare module 'axios/lib/helpers/isAxiosError.js' {
  declare module.exports: $Exports<'axios/lib/helpers/isAxiosError'>;
}
declare module 'axios/lib/helpers/isURLSameOrigin.js' {
  declare module.exports: $Exports<'axios/lib/helpers/isURLSameOrigin'>;
}
declare module 'axios/lib/helpers/null.js' {
  declare module.exports: $Exports<'axios/lib/helpers/null'>;
}
declare module 'axios/lib/helpers/parseHeaders.js' {
  declare module.exports: $Exports<'axios/lib/helpers/parseHeaders'>;
}
declare module 'axios/lib/helpers/parseProtocol.js' {
  declare module.exports: $Exports<'axios/lib/helpers/parseProtocol'>;
}
declare module 'axios/lib/helpers/speedometer.js' {
  declare module.exports: $Exports<'axios/lib/helpers/speedometer'>;
}
declare module 'axios/lib/helpers/spread.js' {
  declare module.exports: $Exports<'axios/lib/helpers/spread'>;
}
declare module 'axios/lib/helpers/throttle.js' {
  declare module.exports: $Exports<'axios/lib/helpers/throttle'>;
}
declare module 'axios/lib/helpers/toFormData.js' {
  declare module.exports: $Exports<'axios/lib/helpers/toFormData'>;
}
declare module 'axios/lib/helpers/toURLEncodedForm.js' {
  declare module.exports: $Exports<'axios/lib/helpers/toURLEncodedForm'>;
}
declare module 'axios/lib/helpers/validator.js' {
  declare module.exports: $Exports<'axios/lib/helpers/validator'>;
}
declare module 'axios/lib/platform/browser/classes/FormData.js' {
  declare module.exports: $Exports<'axios/lib/platform/browser/classes/FormData'>;
}
declare module 'axios/lib/platform/browser/classes/URLSearchParams.js' {
  declare module.exports: $Exports<'axios/lib/platform/browser/classes/URLSearchParams'>;
}
declare module 'axios/lib/platform/browser/index' {
  declare module.exports: $Exports<'axios/lib/platform/browser'>;
}
declare module 'axios/lib/platform/browser/index.js' {
  declare module.exports: $Exports<'axios/lib/platform/browser'>;
}
declare module 'axios/lib/platform/index' {
  declare module.exports: $Exports<'axios/lib/platform'>;
}
declare module 'axios/lib/platform/index.js' {
  declare module.exports: $Exports<'axios/lib/platform'>;
}
declare module 'axios/lib/platform/node/classes/FormData.js' {
  declare module.exports: $Exports<'axios/lib/platform/node/classes/FormData'>;
}
declare module 'axios/lib/platform/node/classes/URLSearchParams.js' {
  declare module.exports: $Exports<'axios/lib/platform/node/classes/URLSearchParams'>;
}
declare module 'axios/lib/platform/node/index' {
  declare module.exports: $Exports<'axios/lib/platform/node'>;
}
declare module 'axios/lib/platform/node/index.js' {
  declare module.exports: $Exports<'axios/lib/platform/node'>;
}
declare module 'axios/lib/utils.js' {
  declare module.exports: $Exports<'axios/lib/utils'>;
}
declare module 'axios/rollup.config.js' {
  declare module.exports: $Exports<'axios/rollup.config'>;
}
