// flow-typed signature: e02430b5a9327e17c07ed42cb8fd197f
// flow-typed version: <<STUB>>/koa-useragent_v^4.1.0/flow_v0.184.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-useragent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-useragent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-useragent/dist' {
  declare module.exports: any;
}

declare module 'koa-useragent/dist/lib/useragent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-useragent/dist/index' {
  declare module.exports: $Exports<'koa-useragent/dist'>;
}
declare module 'koa-useragent/dist/index.js' {
  declare module.exports: $Exports<'koa-useragent/dist'>;
}
declare module 'koa-useragent/dist/lib/useragent.js' {
  declare module.exports: $Exports<'koa-useragent/dist/lib/useragent'>;
}
