// @flow
export type WebHookPayloadT = {
  /**
   * The action that was performed.
   */
  action: | 'assigned'
    | 'auto_merge_disabled'
    | 'auto_merge_enabled'
    // If the action is closed and the merged key is false, the pull request was closed with unmerged commits. If the action is closed and the merged key is true, the pull request was merged.
    | 'closed'
    | 'converted_to_draft'
    // Triggered when a pull request is removed from a merge queue
    | 'dequeued'
    | 'edited'
    // Triggered when a pull request is added to a merge queue
    | 'enqueued'
    | 'labeled'
    | 'locked'
    | 'opened'
    | 'ready_for_review'
    | 'reopened'
    | 'review_request_removed'
    | 'review_requested'
    // Triggered when a pull request's head branch is updated. For example, when the head branch is updated from the base branch, when new commits are pushed to the head branch, or when the base branch is changed.
    | 'synchronize'
    | 'unassigned'
    | 'unlabeled'
    | 'unlocked',
  /**
   * The pull request number.
   */
  number: 2,
  pull_request: {
    url: string,
    id: number,
    node_id: string,
    html_url: string,
    diff_url: string,
    patch_url: string,
    issue_url: string,
    number: number,
    state: string,
    locked: boolean,
    title: string,
    user: {
      login: string,
      id: number,
      node_id: string,
      avatar_url: string,
      gravatar_id: string,
      url: string,
      html_url: string,
      followers_url: string,
      following_url: string,
      gists_url: string,
      starred_url: string,
      subscriptions_url: string,
      organizations_url: string,
      repos_url: string,
      events_url: string,
      received_events_url: string,
      type: string,
      site_admin: false,
    },
    body: string,
    created_at: string,
    updated_at: string,
    closed_at: null,
    merged_at: null,
    merge_commit_sha: null,
    assignee: null,
    assignees: Array<any>,
    requested_reviewers: Array<any>,
    requested_teams: Array<any>,
    labels: Array<any>,
    milestone: null,
    commits_url: string,
    review_comments_url: string,
    review_comment_url: string,
    comments_url: string,
    statuses_url: string,
    head: {
      label: string,
      ref: string,
      sha: string,
      user: {
        login: 'Codertocat',
        id: 21031067,
        node_id: 'MDQ6VXNlcjIxMDMxMDY3',
        avatar_url: 'https://avatars1.githubusercontent.com/u/21031067?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Codertocat',
        html_url: 'https://github.com/Codertocat',
        followers_url: 'https://api.github.com/users/Codertocat/followers',
        following_url: 'https://api.github.com/users/Codertocat/following{/other_user}',
        gists_url: 'https://api.github.com/users/Codertocat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Codertocat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Codertocat/subscriptions',
        organizations_url: 'https://api.github.com/users/Codertocat/orgs',
        repos_url: 'https://api.github.com/users/Codertocat/repos',
        events_url: 'https://api.github.com/users/Codertocat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Codertocat/received_events',
        type: 'User',
        site_admin: false,
      },
      repo: {
        id: 186853002,
        node_id: 'MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=',
        name: 'Hello-World',
        full_name: 'Codertocat/Hello-World',
        private: false,
        owner: {
          login: 'Codertocat',
          id: 21031067,
          node_id: 'MDQ6VXNlcjIxMDMxMDY3',
          avatar_url: 'https://avatars1.githubusercontent.com/u/21031067?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/Codertocat',
          html_url: 'https://github.com/Codertocat',
          followers_url: 'https://api.github.com/users/Codertocat/followers',
          following_url: 'https://api.github.com/users/Codertocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/Codertocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/Codertocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/Codertocat/subscriptions',
          organizations_url: 'https://api.github.com/users/Codertocat/orgs',
          repos_url: 'https://api.github.com/users/Codertocat/repos',
          events_url: 'https://api.github.com/users/Codertocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/Codertocat/received_events',
          type: 'User',
          site_admin: false,
        },
        html_url: 'https://github.com/Codertocat/Hello-World',
        description: null,
        fork: false,
        url: 'https://api.github.com/repos/Codertocat/Hello-World',
        forks_url: 'https://api.github.com/repos/Codertocat/Hello-World/forks',
        keys_url: 'https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/Codertocat/Hello-World/teams',
        hooks_url: 'https://api.github.com/repos/Codertocat/Hello-World/hooks',
        issue_events_url: 'https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}',
        events_url: 'https://api.github.com/repos/Codertocat/Hello-World/events',
        assignees_url: 'https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}',
        branches_url: 'https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}',
        tags_url: 'https://api.github.com/repos/Codertocat/Hello-World/tags',
        blobs_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/Codertocat/Hello-World/languages',
        stargazers_url: 'https://api.github.com/repos/Codertocat/Hello-World/stargazers',
        contributors_url: 'https://api.github.com/repos/Codertocat/Hello-World/contributors',
        subscribers_url: 'https://api.github.com/repos/Codertocat/Hello-World/subscribers',
        subscription_url: 'https://api.github.com/repos/Codertocat/Hello-World/subscription',
        commits_url: 'https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/Codertocat/Hello-World/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}',
        compare_url: 'https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/Codertocat/Hello-World/merges',
        archive_url: 'https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/Codertocat/Hello-World/downloads',
        issues_url: 'https://api.github.com/repos/Codertocat/Hello-World/issues{/number}',
        pulls_url: 'https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/Codertocat/Hello-World/labels{/name}',
        releases_url: 'https://api.github.com/repos/Codertocat/Hello-World/releases{/id}',
        deployments_url: 'https://api.github.com/repos/Codertocat/Hello-World/deployments',
        created_at: '2019-05-15T15:19:25Z',
        updated_at: '2019-05-15T15:19:27Z',
        pushed_at: '2019-05-15T15:20:32Z',
        git_url: 'git://github.com/Codertocat/Hello-World.git',
        ssh_url: 'git@github.com:Codertocat/Hello-World.git',
        clone_url: 'https://github.com/Codertocat/Hello-World.git',
        svn_url: 'https://github.com/Codertocat/Hello-World',
        homepage: null,
        size: 0,
        stargazers_count: 0,
        watchers_count: 0,
        language: null,
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: true,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 2,
        license: null,
        forks: 0,
        open_issues: 2,
        watchers: 0,
        default_branch: 'master',
        allow_squash_merge: true,
        allow_merge_commit: true,
        allow_rebase_merge: true,
        delete_branch_on_merge: false,
      },
    },
    base: {
      label: 'Codertocat:master',
      ref: 'master',
      sha: 'f95f852bd8fca8fcc58a9a2d6c842781e32a215e',
      user: {
        login: 'Codertocat',
        id: 21031067,
        node_id: 'MDQ6VXNlcjIxMDMxMDY3',
        avatar_url: 'https://avatars1.githubusercontent.com/u/21031067?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Codertocat',
        html_url: 'https://github.com/Codertocat',
        followers_url: 'https://api.github.com/users/Codertocat/followers',
        following_url: 'https://api.github.com/users/Codertocat/following{/other_user}',
        gists_url: 'https://api.github.com/users/Codertocat/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Codertocat/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Codertocat/subscriptions',
        organizations_url: 'https://api.github.com/users/Codertocat/orgs',
        repos_url: 'https://api.github.com/users/Codertocat/repos',
        events_url: 'https://api.github.com/users/Codertocat/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Codertocat/received_events',
        type: 'User',
        site_admin: false,
      },
      repo: {
        id: 186853002,
        node_id: 'MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=',
        name: 'Hello-World',
        full_name: 'Codertocat/Hello-World',
        private: false,
        owner: {
          login: 'Codertocat',
          id: 21031067,
          node_id: 'MDQ6VXNlcjIxMDMxMDY3',
          avatar_url: 'https://avatars1.githubusercontent.com/u/21031067?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/Codertocat',
          html_url: 'https://github.com/Codertocat',
          followers_url: 'https://api.github.com/users/Codertocat/followers',
          following_url: 'https://api.github.com/users/Codertocat/following{/other_user}',
          gists_url: 'https://api.github.com/users/Codertocat/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/Codertocat/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/Codertocat/subscriptions',
          organizations_url: 'https://api.github.com/users/Codertocat/orgs',
          repos_url: 'https://api.github.com/users/Codertocat/repos',
          events_url: 'https://api.github.com/users/Codertocat/events{/privacy}',
          received_events_url: 'https://api.github.com/users/Codertocat/received_events',
          type: 'User',
          site_admin: false,
        },
        html_url: 'https://github.com/Codertocat/Hello-World',
        description: null,
        fork: false,
        url: 'https://api.github.com/repos/Codertocat/Hello-World',
        forks_url: 'https://api.github.com/repos/Codertocat/Hello-World/forks',
        keys_url: 'https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/Codertocat/Hello-World/teams',
        hooks_url: 'https://api.github.com/repos/Codertocat/Hello-World/hooks',
        issue_events_url: 'https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}',
        events_url: 'https://api.github.com/repos/Codertocat/Hello-World/events',
        assignees_url: 'https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}',
        branches_url: 'https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}',
        tags_url: 'https://api.github.com/repos/Codertocat/Hello-World/tags',
        blobs_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/Codertocat/Hello-World/languages',
        stargazers_url: 'https://api.github.com/repos/Codertocat/Hello-World/stargazers',
        contributors_url: 'https://api.github.com/repos/Codertocat/Hello-World/contributors',
        subscribers_url: 'https://api.github.com/repos/Codertocat/Hello-World/subscribers',
        subscription_url: 'https://api.github.com/repos/Codertocat/Hello-World/subscription',
        commits_url: 'https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/Codertocat/Hello-World/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}',
        compare_url: 'https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/Codertocat/Hello-World/merges',
        archive_url: 'https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/Codertocat/Hello-World/downloads',
        issues_url: 'https://api.github.com/repos/Codertocat/Hello-World/issues{/number}',
        pulls_url: 'https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/Codertocat/Hello-World/labels{/name}',
        releases_url: 'https://api.github.com/repos/Codertocat/Hello-World/releases{/id}',
        deployments_url: 'https://api.github.com/repos/Codertocat/Hello-World/deployments',
        created_at: '2019-05-15T15:19:25Z',
        updated_at: '2019-05-15T15:19:27Z',
        pushed_at: '2019-05-15T15:20:32Z',
        git_url: 'git://github.com/Codertocat/Hello-World.git',
        ssh_url: 'git@github.com:Codertocat/Hello-World.git',
        clone_url: 'https://github.com/Codertocat/Hello-World.git',
        svn_url: 'https://github.com/Codertocat/Hello-World',
        homepage: null,
        size: 0,
        stargazers_count: 0,
        watchers_count: 0,
        language: null,
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: true,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 2,
        license: null,
        forks: 0,
        open_issues: 2,
        watchers: 0,
        default_branch: 'master',
        allow_squash_merge: true,
        allow_merge_commit: true,
        allow_rebase_merge: true,
        delete_branch_on_merge: false,
      },
    },
    _links: {
      self: {
        href: 'https://api.github.com/repos/Codertocat/Hello-World/pulls/2',
      },
      html: {
        href: 'https://github.com/Codertocat/Hello-World/pull/2',
      },
      issue: {
        href: 'https://api.github.com/repos/Codertocat/Hello-World/issues/2',
      },
      comments: {
        href: 'https://api.github.com/repos/Codertocat/Hello-World/issues/2/comments',
      },
      review_comments: {
        href: 'https://api.github.com/repos/Codertocat/Hello-World/pulls/2/comments',
      },
      review_comment: {
        href: 'https://api.github.com/repos/Codertocat/Hello-World/pulls/comments{/number}',
      },
      commits: {
        href: 'https://api.github.com/repos/Codertocat/Hello-World/pulls/2/commits',
      },
      statuses: {
        href: 'https://api.github.com/repos/Codertocat/Hello-World/statuses/ec26c3e57ca3a959ca5aad62de7213c562f8c821',
      },
    },
    author_association: 'OWNER',
    draft: false,
    merged: false,
    mergeable: null,
    rebaseable: null,
    mergeable_state: 'unknown',
    merged_by: null,
    comments: 0,
    review_comments: 0,
    maintainer_can_modify: false,
    commits: 1,
    additions: 1,
    deletions: 1,
    changed_files: 1,
  },
  repository: {
    id: 186853002,
    node_id: 'MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=',
    name: 'Hello-World',
    full_name: 'Codertocat/Hello-World',
    private: false,
    owner: {
      login: 'Codertocat',
      id: 21031067,
      node_id: 'MDQ6VXNlcjIxMDMxMDY3',
      avatar_url: 'https://avatars1.githubusercontent.com/u/21031067?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Codertocat',
      html_url: 'https://github.com/Codertocat',
      followers_url: 'https://api.github.com/users/Codertocat/followers',
      following_url: 'https://api.github.com/users/Codertocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/Codertocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Codertocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Codertocat/subscriptions',
      organizations_url: 'https://api.github.com/users/Codertocat/orgs',
      repos_url: 'https://api.github.com/users/Codertocat/repos',
      events_url: 'https://api.github.com/users/Codertocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Codertocat/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Codertocat/Hello-World',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/Codertocat/Hello-World',
    forks_url: 'https://api.github.com/repos/Codertocat/Hello-World/forks',
    keys_url: 'https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Codertocat/Hello-World/teams',
    hooks_url: 'https://api.github.com/repos/Codertocat/Hello-World/hooks',
    issue_events_url: 'https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Codertocat/Hello-World/events',
    assignees_url: 'https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Codertocat/Hello-World/tags',
    blobs_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Codertocat/Hello-World/languages',
    stargazers_url: 'https://api.github.com/repos/Codertocat/Hello-World/stargazers',
    contributors_url: 'https://api.github.com/repos/Codertocat/Hello-World/contributors',
    subscribers_url: 'https://api.github.com/repos/Codertocat/Hello-World/subscribers',
    subscription_url: 'https://api.github.com/repos/Codertocat/Hello-World/subscription',
    commits_url: 'https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Codertocat/Hello-World/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Codertocat/Hello-World/merges',
    archive_url: 'https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Codertocat/Hello-World/downloads',
    issues_url: 'https://api.github.com/repos/Codertocat/Hello-World/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Codertocat/Hello-World/labels{/name}',
    releases_url: 'https://api.github.com/repos/Codertocat/Hello-World/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Codertocat/Hello-World/deployments',
    created_at: '2019-05-15T15:19:25Z',
    updated_at: '2019-05-15T15:19:27Z',
    pushed_at: '2019-05-15T15:20:32Z',
    git_url: 'git://github.com/Codertocat/Hello-World.git',
    ssh_url: 'git@github.com:Codertocat/Hello-World.git',
    clone_url: 'https://github.com/Codertocat/Hello-World.git',
    svn_url: 'https://github.com/Codertocat/Hello-World',
    homepage: null,
    size: 0,
    stargazers_count: 0,
    watchers_count: 0,
    language: null,
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 2,
    license: null,
    forks: 0,
    open_issues: 2,
    watchers: 0,
    default_branch: 'master',
  },
  sender: {
    login: 'Codertocat',
    id: 21031067,
    node_id: 'MDQ6VXNlcjIxMDMxMDY3',
    avatar_url: 'https://avatars1.githubusercontent.com/u/21031067?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Codertocat',
    html_url: 'https://github.com/Codertocat',
    followers_url: 'https://api.github.com/users/Codertocat/followers',
    following_url: 'https://api.github.com/users/Codertocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/Codertocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Codertocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Codertocat/subscriptions',
    organizations_url: 'https://api.github.com/users/Codertocat/orgs',
    repos_url: 'https://api.github.com/users/Codertocat/repos',
    events_url: 'https://api.github.com/users/Codertocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Codertocat/received_events',
    type: 'User',
    site_admin: false,
  },
};

export type PullRequestT = {
  data: {
    user: {
      login: string,
    },
  },
};

export type PullRequestFilesT = {
  data: Array<{
    sha: string,
    filename: string,
    status: string,
    additions: number,
    deletions: number,
    changes: number,
    blob_url: string,
    raw_url: string,
    contents_url: string,
    patch: string,
  }>,
};

export type ContentFileT = {
  data: {
    name: string,
    download_url: string,
  },
};

export type IssueCommentsT = {
  data: [
    {
      url: string,
      html_url: string,
      issue_url: string,
      id: number,
      node_id: string,
      user: { ... },
      created_at: string,
      updated_at: string,
      author_association: string,
      body: string,
      reactions: { ... },
      performed_via_github_app: null,
    },
  ],
};
